version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Sao_Paulo
    open-pull-requests-limit: 5
    groups:
      production-minor-and-patch:
        dependency-type: production
        update-types:
          - minor
          - patch
      development-minor-and-patch:
        dependency-type: development
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
    labels:
      - dependencies
    commit-message:
      prefix: deps
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - dependencies
    commit-message:
      prefix: ci
